# github/workflows/ci.yml
name: CI Pipeline

on: 
  push:
    branches: [ main ]
  pull_request:
    branch: [ main ]


jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Run tests
      run: |
        python -m unittest discover tests -v

    - name: Check Python Syntax
      run: |
        python -m py_compile src/*.py tests/*.py
    
    